services:
  - type: worker
    name: pumpbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python webhook_sniper_bot.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AUTHORIZED_USER_ID
        sync: false
