services:
  - type: worker
    name: pumpbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn webhook_sniper_bot:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: AUTHORIZED_USER_ID
        sync: false
