
services:
  - type: worker
    name: pumpbot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python pump_sniper.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TOKEN_MINT
        sync: false
