services:
  - type: web
    name: pumpbot
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"
    startCommand: "uvicorn webhook_sniper_bot:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: BAIL_ON_ZERO_TRADES
        sync: false
